language: node_js

addons:
  sauce_connect: true

dist: xenial

services:
  - xvfb

before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'

install:
  - npm ci || npm install

before_script:
  - npx bower i
  - npm run update-webdriver
  - xvfb-run make test

script:
  - npm run test-travis

after_script:
  - npx -p greenkeeper-lockfile greenkeeper-lockfile-upload

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  
env:
  global:
    secure: rjXS5iQeUkdesaW1RUtTur1ulNhZfhfOF2dlTyG14my80GdAT0g+kmIa2xZI6pB16Im+WJGO4CTzzzHOSetw+shnCHrccz5CTDTMINE1j9hTqP40rAkHDMPA1pOt3fmFbQ5cZxGLtu6BaDkL2Z6mSvQ7exIzMdFmTG36l9lXPGc=
