language: node_js

addons:
  sauce_connect: true

before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
  - npm install -g greenkeeper-lockfile@1

install:
  - npm ci || npm install

before_script:
  - npm i -g bower
  - bower i
  - npm run update-webdriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run test-travis

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  
env:
  global:
    secure: rjXS5iQeUkdesaW1RUtTur1ulNhZfhfOF2dlTyG14my80GdAT0g+kmIa2xZI6pB16Im+WJGO4CTzzzHOSetw+shnCHrccz5CTDTMINE1j9hTqP40rAkHDMPA1pOt3fmFbQ5cZxGLtu6BaDkL2Z6mSvQ7exIzMdFmTG36l9lXPGc=
